package de.blinkt.openvpn.core;
/** Transcribed from ics-openvpn v0.7.65 core/ConnectionStatus.java */
public enum ConnectionStatus {
    LEVEL_CONNECTED, LEVEL_VPNPAUSED, LEVEL_CONNECTING_SERVER_REPLIED,
    LEVEL_CONNECTING_NO_SERVER_REPLY_YET, LEVEL_NONETWORK, LEVEL_NOTCONNECTED,
    LEVEL_START, LEVEL_AUTH_FAILED, LEVEL_WAITING_FOR_USER_INPUT, UNKNOWN_LEVEL;
}
